import CampaignGrid from "@/components/CampaignGrid";
import Footer from "@/components/Footer";
import SearchAppBar from "@/components/Header";
import styles from "@/styles/Home.module.css";
import { Campaigns } from "@/types";
import { Box, Divider, Stack } from "@mui/material";
import { InferGetStaticPropsType } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  //   const res = await fetch('https://.../data')
  //   const data: Campaigns = await res.json()
  let campaigns: Campaigns = {
    campaigns: [
      {
        id: 1,
        title: "hello",
        image:
          "https://amazon-berkeley-objects.s3.us-east-1.amazonaws.com/images/small/00/00a0a32d.jpg",
        link: "#",
      },
      {
        id: 2,
        title: "hello",
        image:
          "https://amazon-berkeley-objects.s3.us-east-1.amazonaws.com/images/small/00/00a0a32d.jpg",
        link: "#",
      },
      {
        id: 3,
        title: "hello",
        image:
          "https://amazon-berkeley-objects.s3.us-east-1.amazonaws.com/images/small/00/00a0a32d.jpg",
        link: "#",
      },
      {
        id: 4,
        title: "hello",
        image:
          "https://amazon-berkeley-objects.s3.us-east-1.amazonaws.com/images/small/00/00a0a32d.jpg",
        link: "#",
      },
      {
        id: 5,
        title: "hello",
        image:
          "https://amazon-berkeley-objects.s3.us-east-1.amazonaws.com/images/small/00/00a0a32d.jpg",
        link: "#",
      },
      {
        id: 6,
        title: "hello",
        image:
          "https://amazon-berkeley-objects.s3.us-east-1.amazonaws.com/images/small/00/00a0a32d.jpg",
        link: "#",
      },
    ],
  };
  let similar = campaigns;
  let personal = campaigns;
  return {
    props: {
      campaigns,
      similar,
      personal,
    },
  };
}

export default function Home({
  campaigns,
  similar,
  personal,
}: InferGetStaticPropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar />
      <main className={styles.main}>
        <Box>
          <Stack
            direction="column"
            spacing={2}
            // divider={<Divider flexItem />}
            justifyContent="center"
            alignItems="center"
          >
            {/* new arrived */}
            <h1>Featured</h1>
            <CampaignGrid campaigns={campaigns.campaigns} />
            {/* similar items */}
            <h1>Hot Trend</h1>
            <CampaignGrid campaigns={similar.campaigns} />
            {/* recommend items */}
            <h1>Recommended</h1>
            <CampaignGrid campaigns={personal.campaigns} />
          </Stack>
        </Box>
      </main>
      <Footer />
    </>
  );
}
